spring:
  datasource:
    #url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:C:/projects/spring5webapp/data/demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password: test20
  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      # ddl-auto: create-drop
      use-new-id-generator-mappings: false